version: '3'
services:
    apache:
        build: .docker/apache
        container_name: sf28_apache
        volumes:
            # Montamos nuestra web desde fuera en el directorio web del contenedor
#            - .docker/config/vhosts:/etc/apache2/sites-enabled
            - .:/var/www/html/sf28
        expose:
            - 80
            - 443
        ports:
            - 80:80
            - 443:443
#        links: 
#            - mysql
        networks:
            - backend

    mysql:
        image: mysql:5.7
        container_name: sf28_mysql
        volumes:
#            - .docker/data/db:/var/lib/mysql
            - .docker/mysql:/docker-entrypoint-initdb.d
        command:
#            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"        
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
#            MYSQL_DATABASE: lugh_dbconnection
#            MYSQL_USER: root
#            MYSQL_PASSWORD: root
        
        networks:
            - backend


networks:
    backend:
        driver: bridge