version: '3'
services:
    apache:
        build: .docker/apache
        container_name: sf28_apache
        volumes:
            # Montamos nuestra web desde fuera en el directorio web del contenedor
            - .docker/config/vhosts:/etc/apache2/sites-enabled
            - .:/home/wwwroot/sf28
        expose:
            - 80
        ports:
            - 8005:80
        links: 
            - mysql

    mysql:
        image: mysql:5.6
        container_name: sf28_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        command:
            - "--default-authentication-plugin=mysql_native_password"
            - "--lower_case_table_names=1"        
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf28
            MYSQL_USER: root
            MYSQL_PASSWORD: root

