security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:          ROLE_USER
        ROLE_USER_FULL:     ROLE_USER_FULL
        ROLE_USER_CERT:     ROLE_USER_CERT
        ROLE_USER_RET:      ROLE_USER_RET
        ROLE_USER_RET:      ROLE_USER_PEN
        ROLE_CUSTOMER:      [ROLE_CUSTOMER, ROLE_USER_FULL]
        ROLE_ADMIN:         [ROLE_ADMIN, ROLE_CUSTOMER] 
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
      
      admin_dbconnection_secured_area:
            pattern: ^/
            host: %path_admin%\.juntadeaccionistas\.es
            anonymous: true
            form_login:
                login_path: fos_user_security_login
                check_path: /user/login_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                use_forward: true
                require_previous_session: false
            logout:
              path: fos_user_security_logout
              
      admin_secured_area:
            pattern: ^/user
            anonymous: true
            provider: fos_userbundle
            context: my_context
            form_login:
                login_path: /user/login
                use_forward: true
                check_path: /user/login_check
                csrf_provider: form.csrf_provider
                require_previous_session: false
            logout:
                path:   /user/logout
                target: /user
    
      main:
            pattern: ^/
            provider: fos_userbundle
            context: my_context
            form_login:
                # csrf_provider: form.csrf_provider @TODO: Poner en producción
                check_path: fos_user_security_check
                success_handler: lugh.authentication.success_handler
                failure_handler: lugh.authentication.failure_handler
                login_path: /home
                use_forward: true
                require_previous_session: false
            logout:       
                success_handler: authentication_handler
            anonymous:    true
            switch_user: { role: ROLE_SUPER_ADMIN, parameter: lugh_1024 }

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/logout, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }  
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/public, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }  
        - { path: ^/rest/v1/publics/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/rest/v1/mails/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/main.js, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/home, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/en, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/es, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/ca, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/gl, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, role: ROLE_CUSTOMER }
        - { path: ^/admin_workspace/, role: ROLE_CUSTOMER }
        - { path: ^/workspace, roles: [ROLE_USER_FULL, ROLE_USER_CERT] }
        - { path: ^/, roles: [ROLE_USER_PEN, ROLE_USER_FULL, ROLE_USER_CERT, ROLE_USER_RET] }
        - { path: ^/, roles: ROLE_SUPER_ADMIN, host: admin.juntadeaccionistas.es }
        - { path: ^/rest/v1/, role: ROLE_USER_FULL }
